sonar.projectKey=DevOps-App
sonar.projectName=DevOps App
sonar.sourceEncoding=UTF-8

sonar.sources=app,frontend/src
sonar.tests=test

sonar.test.inclusions=**/tests/**/*.js,**/*.spec.js,**/*.test.js,**/*_test.py,**/test_*.py

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/coverage/**,**/.pytest_cache/**,**/tests/**,**/*.spec.js,**/*.test.js

sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
